### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Salamandar** [mdsitton/musicgame#6]
Sorry to spam…
Which licenses do you think of ? I hope you think about open source… ;)

**Comment by mdsitton** [comment]
Well right now its a tie between BSD, MIT, and GPLv2 or later.

I was also thinking it would be nice to be able to relicense the code later for whatever reason but that would require me to also have a CLA(Contibuter License Agreement)...
http://oss-watch.ac.uk/resources/cla

If i did a CLA I would probably go with GPLv2 or later, issues with using BSD or MIT are that someone could drive by make it closed source and release a nice game change some stuff maybe make a large profit without any effort...

**Comment by Salamandar** [comment]
Yeah, that's why I prefer GPL too.

**Comment by mdsitton** [comment]
hmm another thought, license the "game" code under GPL and the engine side as BSD lol

Main thing I may want to reuse the engine side of things for something else later on (which may or may not end up being open source idk yet wouldnt be a music game or anything though)

So idk.

**Comment by mdsitton** [comment]
That was where the CLA would be useful, it would give me full rights over all contributed code allowing me to relicense it under something else later. It does adds a bit of extra overhead in order to contribute code though.

**Comment by mdsitton** [comment]
I'm not sure how you will feel about that though... any objections about it?

**Comment by Salamandar** [comment]
Well… The LGPL may be the best choice then.
Wikipedia : The main difference between the GPL and the LGPL is that the latter allows the work to be linked with (in the case of a library, 'used by') a non-(L)GPLed program, regardless of whether it is free software or proprietary software
So you may use some part of your code in non-free software BUT your modified code has to be open source. (I don't think that's terrible if it's not in a public Git repo ^^)
BUUUUUT if someone distributes a modified version of the game, it HAS to be LGPL. That's perfect.

Example : GTK/Qt use LGPL. You can use those toolkits to do proprietary software. But if you modify GTK to your needs, those modifications need to be open source.

**Comment by mdsitton** [comment]
Still after reading through this article might be a decent idea to have one anyways haha.
https://julien.ponge.org/blog/in-defense-of-contributor-license-agreements/

Idk about LGPL for the whole game. Plus if I wanted to reuse the code as LGPL I would need to refactor the engine side of things to support dynamic linking....

Technically I could separate the engine related stuff out into another repository, then leave just the game stuff here... Then license the two seperately.

Personally I don't care if someone takes the engine side of things and forks it to be proprietary. I only care about people forking the game and selling it off as their own or something to that nature. 

So with that in mind, I could put the engine side of things as BSD licensed. The game as GPL v2 or later.

**Comment by mecwerks** [comment]
That sounds like a good idea to me.

**Comment by mdsitton** [comment]
Which idea, there are several over this issue?

**Comment by Salamandar** [comment]
About supporting dynamic linking… You don't need that. Some part of the code can be open source and another not and still be compiled as a whole binary.
And maybe a CLA is great. I never heard about it until now.

**Comment by mecwerks** [comment]
lol sorry reading from my phone :b But splitting the engine and game code. you could probably keep both in same repo and but under different folders and clearly state engine folder is bsd and game folder is gpl or whatever.

**Comment by Salamandar** [comment]
Yes, that could be a possibility.

**Comment by mecwerks** [comment]
and if code is is LGPL you cannot staticly link the code unless you release the rest of the binary unless its specifically stated that you can. which you may as well use GPL at that point

**Comment by mdsitton** [comment]
Yeah exactly

**Comment by mdsitton** [comment]
So I think i'm going to start looking into statically linking the engine side of things since it allows a bit more flexibility in all of this.

**Comment by mdsitton** [comment]
oops ment dynamically...

**Comment by mdsitton** [comment]
Sorry about the slowness on this. I have been busy with my new job. And have been implementing a open source patcher/launcher for a non-free game, because why not.... (Technically it could be adapted for other projects as well)

**Comment by mdsitton** [comment]
Ok so finally decided to go ahead ad do BSD 2 clause, just because its simpler to deal with in some aspects...
